apiVersion: v2
name: truman
description: Helm chart for the Truman application (api, web, jobrunner)
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - truman
  - dotnet
  - web
maintainers:
  - name: TrumanMaintainers
    email: example@example.com
sources:
  - https://github.com/mentaldesk/truman

