version: '3.8'

services:
  truman.api:
    image: truman.api
    build:
      context: .
      dockerfile: Truman.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  web:
    image: truman.web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - truman.api
