apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: truman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: truman.api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgres;Database=trumandb;Username=truman;Password=devpassword"
            - name: ASPNETCORE_ENVIRONMENT
              value: Development 