apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: truman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: truman-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: truman-config
                  key: POSTGRES_HOST
          envFrom:
            - secretRef:
                name: truman-env 