apiVersion: v1
kind: ConfigMap
metadata:
  name: truman-config
  namespace: truman
data:
  VITE_API_URL: "http://localhost:5001"
  VITE_ENVIRONMENT: "kind"
  POSTGRES_HOST: "postgres.truman.svc.cluster.local"