apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: truman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: truman-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: truman-config
                  key: VITE_API_URL
          envFrom:
            - secretRef:
                name: truman-env 