apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: truman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: truman.web
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80 