apiVersion: batch/v1
kind: CronJob
metadata:
  name: jobrunner
  namespace: truman
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: jobrunner
            image: truman-jobrunner:latest
            imagePullPolicy: IfNotPresent
            env:
              - name: POSTGRES_HOST
                valueFrom:
                  configMapKeyRef:
                    name: truman-config
                    key: POSTGRES_HOST
            envFrom:
              - secretRef:
                  name: truman-env 
          restartPolicy: OnFailure 