apiVersion: v1
kind: Service
metadata:
  name: {{ include "truman.fullname" . }}-api
  namespace: {{ .Values.namespace.name }}
  labels:
    component: api
    {{- include "truman.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  selector:
    component: api
    {{- include "truman.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.api.containerPort }}
      name: http

