apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "truman.fullname" . }}-jobrunner
  namespace: {{ .Values.namespace.name }}
  labels:
    component: jobrunner
    {{- include "truman.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.jobrunner.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            component: jobrunner
            {{- include "truman.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: jobrunner
              image: "{{ .Values.image.jobrunner.repository }}:{{ .Values.image.jobrunner.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: POSTGRES_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "truman.configmap.name" . }}
                      key: POSTGRES_HOST
              {{- if .Values.jobrunner.extraEnv }}
              {{- toYaml .Values.jobrunner.extraEnv | nindent 14 }}
              {{- end }}
              envFrom:
                - secretRef:
                    name: {{ include "truman.secret.name" . }}
              resources:
                {{- toYaml .Values.jobrunner.resources | nindent 16 }}

